### ISSUE TITLE
Offer different views: milestones/labels/projects

### ISSUE THREAD

**Issue by digitalronin** [digitalronin/knuckle-dragger#14]
- [x] View issues by contributor
- [ ] View issues by milestone
- [ ] View issues by label
- [ ] View issues by project

blocks #7
